#!/usr/bin/python3

i = 4
d = 4.0
s = 'HackerRank '
# Declare second integer, double, and String variables.

# Read and save an integer, double, and String to your variables.

# Print the sum of both integer variables on a new line.

# Print the sum of the double variables on a new line.

# Concatenate and print the String variables on a new line
# The 's' variable above should be printed first.

input1 = input()
inputInt = int(input1)

input2 = input()
inputDouble = float(input2)

input3 = input()


result1 = i + inputInt
result2 = d + inputDouble
result3 = s + input3

print(result1)
print(result2)
print(result3)