#!/bin/python3

import math
import os
import random
import re
import sys

def conditionals(n):
    if (n % 2 == 0):
        if (n >= 2 and n <= 5):
            print("Not Weird")

        elif(n > 20):
            print("Not Weird")
        else:
            print("Weird")
    else:
        print("Weird")


if __name__ == '__main__':
    n = int(input().strip())
    conditionals(n)
